[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["Brett Stevenson <bstevensondev@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"
pathfinding = "4"
regex = "1"
